---
name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    uses: sulaiman-coder/go-release-workflow/.github/workflows/release.yaml@v0.4.3 # v0.4.3
    with:
      go-version: 1.21.0
      khulnasoft_version: v2.10.1
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}
    permissions:
      contents: write
      id-token: write
      actions: read
