---
name: test
on: pull_request
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@v0.2.2 # v0.2.2
    with:
      khulnasoft_version: v2.10.1
      go-version: 1.21.0
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}
    permissions:
      pull-requests: write
      contents: read # To checkout private repository
